name: Pull Request Workflow - Build and test

on: pull_request

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: Coverage report
        path: coverage
